# Generated by Django 4.2 on 2023-04-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_auth_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auth_type_choices',
            new_name='auth_type',
        ),
    ]
