# Generated by Django 4.2 on 2023-04-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_auth_type_choices_user_auth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('via_email', 'via_email'), ('via_phone', 'via_phone'), ('via_username', 'via_username')], default='via_username', editable=False, max_length=31),
        ),
    ]
